### ISSUE TITLE
I'm getting permission denied when compiling the kernel 

### ISSUE THREAD

**Issue by charlieporth1** [alexey6600/mm_sony_tetra_3.14#3]
I'm getting permission denied when compiling the kernel 

Here's what I'm getting 

 chronos@localhost /home/user/a9705a9f11dba0e2ce42520169c81137cba9e81c/Downloads $ cd /home/user/a9705a9f11dba0e2ce42520169c81137cba9e81c/Downloads/mm_sony_tetra_3.14-master
chronos@localhost /home/user/a9705a9f11dba0e2ce42520169c81137cba9e81c/Downloads/mm_sony_tetra_3.14-master $ make
  HOSTCC  scripts/basic/fixdep
/bin/sh: scripts/basic/fixdep: Permission denied
make[2]: *** [scripts/basic/fixdep] Error 126
make[1]: *** [scripts_basic] Error 2
  SYSHDR  arch/x86/syscalls/../include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/syscalls/../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/syscalls/../include/generated/uapi/asm/unistd_x32.h
  SYSTBL  arch/x86/syscalls/../include/generated/asm/syscalls_32.h
  HOSTCC  scripts/basic/fixdep
/bin/sh: scripts/basic/fixdep: Permission denied
make[1]: *** [scripts/basic/fixdep] Error 126
make: *** [scripts_basic] Error 2
chronos@localhost /home/user/a9705a9f11dba0e2ce42520169c81137cba9e81c/Downloads/mm_sony_tetra_3.14-master $ 

That's straight from the terminal 

if it helps I'm on Chrone OS and not crouton just pure ChromeOS

**Comment by alexey6600** [comment]
Are you compile kernel under root? 
If no- set right permissions for the user that make compile.

PS. I think GitHub's Issue topic should not include issues such as this.

**Comment by charlieporth1** [comment]
I did try root that's why it's an issue. I also am proficient in Linux terminals both  debain based and BSD. I tried chmod and chown too, so I don't know what else to do?

**Comment by charlieporth1** [comment]
I did try root that's why it's an issue. I also am proficient in Linux terminals both  debain based and BSD. I tried chmod and chown too, so I don't know what else to do?

**Comment by alexey6600** [comment]
1. Toolchain?
2. Privileges?
3. OS?
4. Paths, permissions?
5. FS mount options (noexec flag)?
I'm using RHEL based OS for a while, and don't have such problems.

**Comment by charlieporth1** [comment]
I switched OS is and tried ubuntu for this, it worked but when compiling the kernel I got 


ubuntu@tegra-ubuntu:~/Downloads/mm_sony_tetra_3.14-master$ sudo make -j 3 && make modules_install && make install
[sudo] password for ubuntu:
Sorry, try again.
[sudo] password for ubuntu:
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTCC  scripts/kallsyms
  CC      scripts/mod/empty.o
gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together
scripts/Makefile.build:308: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 1
scripts/Makefile.build:455: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: 'include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
gcc: error: -mfloat-abi=soft and -mfloat-abi=hard may not be used together
/home/ubuntu/Downloads/mm_sony_tetra_3.14-master/./Kbuild:35: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
Makefile:844: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
make: *** Waiting for unfinished jobs....
Makefile:521: recipe for target 'scripts' failed
make: *** [scripts] Error 2
ubuntu@tegra-ubuntu:~/Downloads/mm_sony_tetra_3.14-master$ gcc
gcc: fatal error: no input files
compilation terminated.
ubuntu@tegra-ubuntu:~/Downloads/mm_sony_tetra_3.14-master$ sudo make -j 3 && make modules_install && make install

**Comment by alexey6600** [comment]
How crossco,piler do you use?
